modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"
[[mods]]
modId="superbium"
version="${version}"
displayName="superbium"
#logoFile="assets/nvidium/nvidium.png"
authors="Cortex, Ferri_Arnus"
description='''
Experimental port of nvidium, bugs will be present
Replacement rendering engine for sodium/embeddium
'''