modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0"
[[mods]]
modId="nvidium"
version="${version}"
displayName="nvidium"
logoFile="assets/nvidium/nvidium.png"
authors="Cortex"
description='''
Replacement rendering engine for sodium/embeddium
'''